apiVersion: v1
kind: Pod
metadata:
  name: hway
  labels:
    app: hway
spec:
  serviceAccountName: secrets # This is important as it links the pod to the IAM role via IRSA
  volumes:
  - name: user-creds
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws-secrets"
  containers:
  - name: hway
    image: njibrigthain100/brigthain:hwv1
    volumeMounts:
    - name: user-creds
      mountPath: "/mnt/secrets-store"
      readOnly: true
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: rds-secrets
          key: DB_USERNAME
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: rds-secrets
          key: DB_PASSWORD
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: rds-secrets
          key: DB_HOST
    - name: ANSIBLE_USERNAME
      valueFrom:
        secretKeyRef:
          name: ansible-secrets
          key: DB_USERNAME
    - name: ANSIBLE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ansible-secrets
          key: ANSIBLE_PASSWORD
    - name: ANSIBLE_PORT
      valueFrom:
        configMapKeyRef:
          name: secrets-config
          key: ANSIBLE_PORT
    ports:
    - containerPort: 80
