apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: v3
  template:
    metadata:
      labels:
        app: v3
    spec:
      containers:
      - name: v3
        image: njibrigthain100/brigthain:v3
        ports:
        - containerPort: 80
