apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: it
  template:
    metadata:
      labels:
        app: it
    spec:
      containers:
      - name: it
        image: njibrigthain100/brigthain:it
        ports:
        - containerPort: 8080
