apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "int-preproduction-use1-shared-eks-mysql-db/rds-credentials20260104192941118700000001" # Name of the secret in AWS Secrets Manager
        objectType: "secretsmanager" # Type of the secret (secretsmanager or ssmparameter)
    jmesPath: |
      - path: username
        objectAlias: DB_USERNAME
      - path: password
        objectAlias: DB_PASSWORD
      - path: host
        objectAlias: DB_HOST
    objects: |
      - objectName: "int-preproduction-use1-ansible-authentication2025122219263128620000000a" # Name of the secret in AWS Secrets Manager
        objectType: "secretsmanager" # Type of the secret (secretsmanager or ssmparameter)
    jmesPath: |
      - path: username
        objectAlias: ANSIBLE_USERNAME
      - path: password
        objectAlias: ANSIBLE_PASSWORD
  secretObjects:                      
  - secretName: rds-secrets   
    type: Opaque
    data:
    - objectName: DB_USERNAME # This is the objectAlias defined above
      key: DB_USERNAME  # This is the key in the Kubernetes secret
    - objectName: DB_PASSWORD
      key: DB_PASSWORD
    - objectName: DB_HOST
      key: DB_HOST
  - secretName: ansible-secrets   
    type: Opaque
    data:
    - objectName: ANSIBLE_USERNAME 
      key: ANSIBLE_USERNAME  
    - objectName: ANSIBLE_PASSWORD
      key: ANSIBLE_PASSWORD