apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "int-preproduction-use1-shared-user-credentials20251222192402582800000001" # Name of the secret in AWS Secrets Manager
        objectType: "secretsmanager" # Type of the secret (secretsmanager or ssmparameter)
