AWSTemplateFormatVersion: '2010-09-09'
Description: SSM Automation Document for all linux servers to join domain and add to sudoers file

Parameters:
  pAwsAccount:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccount
  
  pAwsAccountLC:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccountLC

  pAppName:
    Type: String
    Default: cognitech

  pSSMDomainJoinDoc:
    Description: The Domain join document 
    Type: String

  pSSMSudoersFile:
    Description: The ssm document to add linux users to sudoers file
    Type: String

  pLinuxPackageInstall:
    Description: Installs linux packages 
    Type: String

Resources:
  rLinuxSSMDocument:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Automation
      Content:
        schemaVersion: '0.3'
        description: Joins the linux server to the domain
        mainSteps:
          - name: AddLinuxInstancetoDomain
            action: 'aws:executeAutomation'
            OnFailure: Abort
            inputs:
              DocumentName: !Sub ${ pAwsAccount }-${ pAppName }-DomainJoinDoc
            NextStep: Addservertosudoersfile
            
          - name: Addservertosudoersfile
            action: 'aws:executeAutomation'
            OnFailure: Abort
            inputs:
              DocumentName: !Ref pSSMSudoersFile
            NextStep: InstallLinuxPackages

          - name: InstallLinuxPackages
            action: aws:executeAutomation'
            OnFailure: Abort
            inputs:
              DocumentName: !Ref pLinuxPackageInstall


Outputs:
  orLinuxSSMDocument:
    Description: The name of the SSM Automation Document
    Value: !Ref rLinuxSSMDocument
