AWSTemplateFormatVersion: 2010-09-09
Description: Configure the AWSCloudFormationStackSetExecutionRole to enable use of your account as a target account in AWS CloudFormation StackSets.

Parameters:
  AdministratorAccountId:
    Type: String
    Description: AWS Account Id of the administrator account (the account in which StackSets will be created).
    MaxLength: 12
    MinLength: 12
  ExecutionRoleName:
    Type: String
    Default: AWSCloudFormationStackSetExecutionRole
    Description: "The name of the execution role. Defaults to 'AWSCloudFormationStackSetExecutionRole'."

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ExecutionRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref AdministratorAccountId
              Service: ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      # ManagedPolicyArns:
      #   - !Ref StacksetPolicy
  StacksetPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for stackset creation, update and deletion 
      PolicyDocument:
           Version: 2012-10-17 
           Statement: 
              - Effect: Allow 
                Action: 
                  - "Cloudformation:*" 
                  - "S3:*"
                  - "SSM:*"
                  - "ec2:*"
                Resource: "*" 
              - Effect: Allow 
                Action:
                  - "iam:PassRole"
                Resource: 
                - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${ExecutionRoleName}'
      Roles: 
        - !Ref ExecutionRole
