AWSTemplateFormatVersion: '2010-09-09'
Description: Stops multiple EC2 instances based on the provided instance IDs.

Parameters:
  InstanceIds:
    Type: CommaDelimitedList
    Description: List of EC2 instance IDs to stop

Resources:
  TriggerLambda:
    Type: Custom::StartStopEC2Instance
    Properties:
      ServiceToken: arn:aws:lambda:us-east-1:485147667400:function:prod-StopMultipleInstances
      InstanceIds: !Ref InstanceIds

Outputs:
  LambdaInvocation:
    Description: Lambda was triggered with the provided EC2 Instance ID
    Value: !Join [",", !Ref InstanceIds]
