apiVersion: v1
kind: Pod
metadata:
  name: nginx # Name of the Pod
  namespace: demo # Specify the namespace
spec:
  # short for specification
  containers:
  - name: my-first-container
    image: nginx:latest # Use the official Nginx image from Docker Hub
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-quota
  namespace: demo
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
