# =============================================================================
# Complete AWS Secrets Manager + CSI Driver Example
# =============================================================================
---
# 1. Service Account with IRSA (IAM Role for Service Account)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: default
  annotations:
    # Link to IAM role that has permission to access Secrets Manager
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/eks-secrets-manager-role
---
# 2. SecretProviderClass - Defines which secrets to fetch from AWS
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-db-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    # Fetch secrets from AWS Secrets Manager
    objects: |
      - objectName: "prod/db/credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: DB_USER
          - path: password
            objectAlias: DB_PASSWORD
          - path: host
            objectAlias: DB_HOST
          - path: port
            objectAlias: DB_PORT
          - path: database
            objectAlias: DB_NAME
  # Optional: Create a Kubernetes Secret for environment variable injection
  secretObjects:
  - secretName: db-secret
    type: Opaque
    data:
    - objectName: DB_USER
      key: username
    - objectName: DB_PASSWORD
      key: password
    - objectName: DB_HOST
      key: host
    - objectName: DB_PORT
      key: port
    - objectName: DB_NAME
      key: database
---
# 3. Deployment - Application using the secrets
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: app-service-account # CRITICAL: Links pod to IAM role

      containers:
      - name: app
        image: my-app:latest

        # Method 1: Environment variables from Kubernetes Secret
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database

        # Alternative Method 2: Inject all secrets as env vars at once
        # envFrom:
        #   - secretRef:
        #       name: db-secret

        # Method 3: Mount secrets as files (always available)
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true

      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "aws-db-secrets"
---
# 4. Example: Multiple Secrets from Different Sources
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: multi-source-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      # Database credentials from Secrets Manager
      - objectName: "prod/db/credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: db_user
          - path: password
            objectAlias: db_pass

      # API keys from SSM Parameter Store
      - objectName: "/prod/api/key"
        objectType: "ssmparameter"
        objectAlias: api_key

      # Third-party credentials
      - objectName: "prod/external/stripe"
        objectType: "secretsmanager"
        jmesPath:
          - path: secret_key
            objectAlias: stripe_secret

  secretObjects:
  - secretName: app-secrets
    type: Opaque
    data:
    - objectName: db_user
      key: DB_USER
    - objectName: db_pass
      key: DB_PASSWORD
    - objectName: api_key
      key: API_KEY
    - objectName: stripe_secret
      key: STRIPE_SECRET
