AWSTemplateFormatVersion: 2010-09-09
Description: Creates the directory service 

Parameters: 
  pAwsAccount:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccount
  
  pAwsAccountLC:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccountLC
  
  pAppName:
    Description: The app cosuming these resources
    Type: String
  
  pAdminPassowrd:
    Description: The password for the default administrative user named Admin
    Type: String
  
  pADName:
    Description: The directory DNS name
    Type: String
    Default: kahbrigthllc.com
  
  pApp1PrivateSubnet1Id:
    Description: The Id of the first App1 private subnet 
    Type: String

  pApp1PrivateSubnet2Id:
    Description: The Id of the second App1 private subnet
    Type: String
 
  pApp1VPCId:
    Description: The Id of the App1 VPC
    Type: String
 
  pADShortName:
    Description: The NetBIOS name for your domain
    Type: String
    Default: kahbrigthllc

  pEdition:
    Description: The directory edition 
    Type: String
    AllowedValues:
      - "Enterprise"
      - "Standard"
  

 
Resources: 
  rNestedActiveDirectory: 
    Type: AWS::DirectoryService::MicrosoftAD
    Properties: 
      Name: !Ref pADName
      Edition: !Ref pEdition
      Password: 
        !Ref pAdminPassowrd
      ShortName: 
        !Ref pADShortName
      VpcSettings: 
        SubnetIds: 
          - !Ref pApp1PrivateSubnet1Id
          - !Ref pApp1PrivateSubnet2Id
        VpcId: 
          !Ref pApp1VPCId
Outputs:
  oDirectoryId:
    Description: The ID of the created directory 
    Value: !Ref rNestedActiveDirectory
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-directoryId 

  oDirectoryName:
    Description: The name of the created directory 
    Value: !Ref pADName
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-directoryName 
  
  oDirectoryDNSIpaddresses:
    Description: The DNS Ipaddresses of the created directory 
    Value: !Join [", ", !GetAtt rNestedActiveDirectory.DnsIpAddresses]
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-DNSIpaddresses
  



