AWSTemplateFormatVersion: 2010-09-09
Description: Creates the directory service 

Parameters: 
  pAwsAccount:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccount
  
  pAwsAccountLC:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccountLC
  
  pAppName:
    Description: The app cosuming these resources
    Type: String
  
  pAdminPassowrd:
    Description: The password for the default administrative user named Admin
    Type: String
  
  pADName:
    Description: The directory DNS name
    Type: String
    Default: kahbrigthllc.com
  
  pSharedServicesPrivateSubnet1Id:
    Description: The subnet in which to create the domain controllers
    Type: String

  pSharedServicesPrivateSubnet2Id:
    Description: The subnet in which to create the domain controllers
    Type: String
 
  pSharedServicesVPCId:
    Description: The VPC in which to create the directory service
    Type: String
 
  pADShortName:
    Description: The NetBIOS name for your domain
    Type: String
    Default: kahbrigthllc
 
Resources: 
  rNestedActiveDirectory: 
  Type: AWS::DirectoryService::MicrosoftAD
  Properties: 
    Name: !Ref pADName
    Password: 
      Ref: !Ref pAdminPassowrd
    ShortName: 
      Ref: !Ref pADShortName
    VpcSettings: 
      SubnetIds: 
        - Ref: !Ref pSharedServicesPrivateSubnet1Id
        - Ref: !Ref pSharedServicesPrivateSubnet2Id
      VpcId: 
        Ref: !Ref pSharedServicesVPCId

Outputs: