AWSTemplateFormatVersion: 2010-09-09
Description: Creates the security groups for all the ec2 instances

Parameters: 
  pAwsAccount:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccount
  
  pAwsAccountLC:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccountLC

  pAppName:
    Description: The app cosuming these resources
    Type: String
    Default: cognitech

  pSharedServicesVPCCidr: 
    Description: The shared services vpc Id 
    Type: String 

  pSharedServicesVPCId:
    Description: The Id of the shared services VPC
    Type: String

  pApp1VPCId:
    Description: The Id of the App1 VPC
    Type: String

Resources: 
  rNestedadbsg:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: The active directory security group 
      GroupName: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-AD-sg
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: !Ref pSharedServicesVPCCidr
          Description: "Allow RDP access from the bastion security group"
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-AD-sg
      VpcId: !Ref pApp1VPCId
  rNestedsshbastionsg:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: ssh bastion security group
      GroupName: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ssh-bastion
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: "Allow SSH access from the internet"
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ssh-bastion
      VpcId: !Ref pSharedServicesVPCId

  rNestedrdpbastionsg:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: rdp bastion security group
      GroupName: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-rdp-bastion
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0
          Description: "Allow RDP access from the internet"
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-rdp-bastion
      VpcId: !Ref pSharedServicesVPCId
 
Outputs:
  oNestedadsg:
    Description: The active directory master server security group id 
    Value: !Ref rNestedadbsg
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ad-sg

  oNestedsshbastionsg:
    Description: The ssh bastion security group Id
    Value: !Ref rNestedsshbastionsg
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ssh-bastion-sg
  
  oNestedrdpbastionsg:
    Description: The rdp bastion security group Id 
    Value: !Ref rNestedrdpbastionsg
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-rdp-bastion-sg
  
  