AWSTemplateFormatVersion: 2010-09-09
Description: Sets up Data Lifecylce Manager
Parameters: 
  pAwsAccount:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccount
  
  pAwsAccountLC:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccountLC
    
  pAppName:
    Type: String
    Default: cognitech
Resources: 
  rNestedBasicLifecyclePolicy:
    Type: AWS::DLM::LifecyclePolicy
    Properties:
      Description: Lifecycle Policy using CloudFormation
      State: ENABLED
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/service-role/AWSDataLifecycleManagerDefaultRole
      PolicyDetails:
        ResourceTypes:
        - VOLUME
        TargetTags:
        - Key: backup 
          Value: '!Sub ${ AWS::Region}-daily'
        Schedules:
        - Name: !Sub ${ pAwsAccount }-${ pAppName }-Daily-Snapshots
          TagsToAdd:
          - Key: type
            Value: DailySnapshot
          CreateRule:
            Interval: 12
            IntervalUnit: HOURS
            Times:
            - '01:00'
          RetainRule:
            Count: 1
          CopyTags: true
          CrossRegionCopyRules:
          - Encrypted: false
            Target: us-east-1
