AWSTemplateFormatVersion: 2010-09-09
Description: Creates the SSM document for directory services

Parameters: 
  pAwsAccount:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccount
  
  pAwsAccountLC:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccountLC
    
  pAppName:
    Description: The app cosuming these resources
    Type: String  

  pDirectoryId:
    Description: The ID of the AWS Directory Service directory
    Type: String

  
  pDirectoryName:
    Description: The name of the directory. For example, test.example.com
    Type: String

  
  pDNSIpAddresses:
    AllowedPattern: "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
    Description: The IP addresses of the DNS servers in the directory
    Type: CommaDelimitedList

    
 
Resources: 
  rNestedDomainJoinDocument: 
    Type: AWS::SSM::Document
    Properties: 
      Name: !Sub ${ pAwsAccount }-${ pAppName }-DomainJoinDoc
      Content:
        schemaVersion: '1.2'
        description: Join instances to an AWS Directory Service domain.
        runtimeConfig:
          aws:domainJoin:
            properties:
              directoryId: !Ref pDirectoryId
              directoryName: !Ref pDirectoryName
              dnsIpAddresses: !Ref pDNSIpAddresses
  
Outputs:
  oDomainJoinDocument:
    Description: The name of the ssm domain join document
    Value: !Ref rNestedDomainJoinDocument
    Export: 
      Name: !Sub ${ pAwsAccount }-${ pAppName }-DomainJoinDoc





