AWSTemplateFormatVersion: '2010-09-09'
Description: Creates vpc and subnets for apps and shared services     
Parameters: 
  pAwsAccount:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccount
  
  pAwsAccountLC:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccountLC

  pAppName:
    Description: The app cosuming these resources
    Type: String

#########################################App VPC#############################################################  
  pVPCCidr:
    Description: The cidr block of the vpc being created
    Type: String
  
  pPrivateSubnet1CIDR:
    Description: The cidr block for the first private subnet
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
     
  pPrivateSubnet2CIDR:
    Description: The cidr block for the second private subnet
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
    
  
  pPublicSubnet1CIDR:
    Description: The cidr block for the first public subnet
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
    
  
  pPublicSubnet2CIDR:
    Description: The cidr block for the second public subnet
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
    
  
  pAvailabilityZones:
    Description: The availability zones on which to create the resources
    Type: CommaDelimitedList
    
  pSharedServicesAccount:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/SharedServicesVpc
  
###################################Shared services VPC######################################################  
  pSharedServicesVPCCidr:
    Description: The cidr block of the shared services vpc being created
    Type: String

  pSharedServicesPrivateSubnet1CIDR:
    Description: The cidr block for the first shared services private subnet
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String

  pSharedServicesPrivateSubnet2CIDR:
    Description: The cidr block for the second private subnet
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String

  pSharedServicesPublicSubnet1CIDR:
    Description: The cidr block for the first public subnet
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
 
  pSharedServicesPublicSubnet2CIDR:
    Description: The cidr block for the second public subnet
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String

  pSharedServicesAvailabilityZones:
    Description: The availability zones on which to create the resources
    Type: CommaDelimitedList

Resources: 
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html#cfn-aws-ec2-vpc-instancetenancy
 ###########################################App VPC######################################################## 
  rNestedAppVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref pVPCCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      # dedicated | default | host
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-vpc

  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-internetgateway.html
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc-gateway-attachment.html
  rNestedAppInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-InternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref rNestedVPC
      InternetGatewayId: !Ref rNestedInternetGateway
    
  rNestedAppNatGateway1:
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId: !GetAtt rNestedElasticIP1.AllocationId
      SubnetId: !Ref rNestedPublicSubnet1
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ngw1
  
  rNestedAppElasticIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  
  rNestedNatGateway2:
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId: !GetAtt rNestedElasticIP2.AllocationId
      SubnetId: !Ref rNestedPublicSubnet2
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ngw2

  rNestedAppElasticIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html
  rNestedAppPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select [0, !Ref pAvailabilityZones]
      CidrBlock: !Ref pPrivateSubnet1CIDR
      VpcId: !Ref rNestedVPC
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-private-subnet-1

  rNestedAppPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select [1, !Ref pAvailabilityZones]
      CidrBlock: !Ref pPrivateSubnet2CIDR
      VpcId: !Ref rNestedVPC
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-private-subnet-2

  rNestedAppPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select [0, !Ref pAvailabilityZones]
      CidrBlock: !Ref pPublicSubnet1CIDR
      VpcId: !Ref rNestedVPC
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-public-subnet-1

  rNestedAppPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select [1, !Ref pAvailabilityZones]
      CidrBlock: !Ref pPublicSubnet2CIDR
      VpcId: !Ref rNestedVPC
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-public-subnet-2

   # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-route-table.html
  rNestedAppPublicSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref rNestedVPC 
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-public-subnet1-rt

  rNestedAppPublicSubnet2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref rNestedVPC 
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-public-subnet2-rt
  
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-route.html
  rNestedAppPublicSubnet1Route:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref rNestedInternetGateway
      RouteTableId: !Ref rNestedPublicSubnet1RouteTable

  rNestedAppPublicSubnet2Route:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref rNestedInternetGateway
      RouteTableId: !Ref rNestedPublicSubnet2RouteTable

  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet-route-table-assoc.html
  rNestedAppPublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref rNestedPublicSubnet1RouteTable
      SubnetId: !Ref rNestedPublicSubnet1

  rNestedAppPublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref rNestedPublicSubnet2RouteTable
      SubnetId: !Ref rNestedPublicSubnet2

###########################################Shared Services VPC################################################# 
  rNestedSharedServicesVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref pVPCCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      # dedicated | default | host
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-vpc

  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-internetgateway.html
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc-gateway-attachment.html
  rNestedSharedServicesInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-InternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref rNestedVPC
      InternetGatewayId: !Ref rNestedInternetGateway
    
  rNestedSharedServicesNatGateway1:
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId: !GetAtt rNestedElasticIP1.AllocationId
      SubnetId: !Ref rNestedSharedServicesPublicSubnet1
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-ngw1
  
  rNestedSharedServicesElasticIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  
  rNestedSharedServicesNatGateway2:
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId: !GetAtt rNestedElasticIP2.AllocationId
      SubnetId: !Ref rNestedSharedServicesPublicSubnet2
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-ngw2

  rNestedSharedServicesElasticIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html
  rNestedSharedServicesPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select [0, !Ref pAvailabilityZones]
      CidrBlock: !Ref pSharedServicesPrivateSubnet1CIDR
      VpcId: !Ref rNestedSharedServicesVPC
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-private-subnet-1

  rNestedSharedServicesPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select [1, !Ref pAvailabilityZones]
      CidrBlock: !Ref pSharedServicesPrivateSubnet2CIDR
      VpcId: !Ref rNestedVPC
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-private-subnet-2

  rNestedSharedServicesPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select [0, !Ref pAvailabilityZones]
      CidrBlock: !Ref pSharedServicesPublicSubnet1CIDR
      VpcId: !Ref rNestedSharedServicesVPC
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-public-subnet-1

  rNestedSharedServicesPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select [1, !Ref pAvailabilityZones]
      CidrBlock: !Ref pSharedServicesPublicSubnet1CIDR
      VpcId: !Ref rNestedSharedServicesVPC
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-public-subnet-2

   # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-route-table.html
  rNestedSharedServicesPublicSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref rNestedSharedServicesVPC
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-public-subnet1-rt

  rNestedSharedServicesPublicSubnet2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref rNestedSharedServicesVPC
      Tags: 
        - Key: Name 
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-public-subnet2-rt
  
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-route.html
  rNestedSharedServicesPublicSubnet1Route:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref rNestedSharedServicesInternetGateway
      RouteTableId: !Ref rNestedSharedServicesPublicSubnet1RouteTable

  rNestedSharedServicesPublicSubnet2Route:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref rNestedSharedServicesInternetGateway
      RouteTableId: !Ref rNestedSharedServicesPublicSubnet2RouteTable

  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet-route-table-assoc.html
  rNestedSharedServicesPublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref rNestedSharedServicesPublicSubnet1RouteTable
      SubnetId: !Ref rNestedSharedServicesPublicSubnet1

  rNestedSharedServicesPublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref rNestedSharedServicesPublicSubnet2RouteTable
      SubnetId: !Ref rNestedSharedServicesPublicSubnet2
   
Outputs:
  oAppVPC:
    Description: The ID of the vpc
    Value: !Ref rNestedVPC
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-vpc
      
  oAppPrivateSubnet1:
    Description: The ID of the private subnet
    Value: !Ref rNestedPrivateSubnet1
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-private-subnet1
  
  oAppPrivateSubnet2:
    Description: The ID of the private subnet
    Value: !Ref rNestedPrivateSubnet2
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-private-subnet2

  oAppPublicSubnet1:
    Description: The ID of the private subnet
    Value: !Ref rNestedPublicSubnet1
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-public-subnet1

  oAppPublicSubnet2:
    Description: The ID of the private subnet
    Value: !Ref rNestedPublicSubnet2
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-public-subnet2

  oAppInternetGateway:
    Description: The ID of the internetgateway
    Value: !Ref rNestedInternetGateway
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-igw

  oAppNatGateway1:
    Description: The ID of the first Natgateway
    Value: !Ref rNestedNatGateway1
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ngw1

  oAppNatGateway2:
    Description: The ID of the second Natgateway
    Value: !Ref rNestedNatGateway2
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ngw2

#############################################Shared services ############################################ 
  oSharedServicesVPC:
    Description: The ID of the shared services vpc
    Value: !Ref rNestedSharedServicesVPC
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-vpc
      
  oSharedServicesPrivateSubnet1:
    Description: The ID of the shared services 1st private subnet
    Value: !Ref rNestedSharedServicesPrivateSubnet1
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-private-subnet1
  
  oSharedServicesPrivateSubnet2:
    Description: The ID of the shared services 2nd private subnet
    Value: !Ref rNestedSharedServicesPrivateSubnet2
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-private-subnet2

  oSharedServicesPublicSubnet1:
    Description: The ID of the shared services 1st public subnet 
    Value: !Ref rNestedSharedServicesPublicSubnet1
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-public-subnet1

  oSharedServicesPublicSubnet2:
    Description: The ID of the shared services 2nd public subnet
    Value: !Ref rNestedSharedServicesPublicSubnet2
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-public-subnet2

  oSharedServicesInternetGateway:
    Description: The ID of the shared services internetgateway
    Value: !Ref rNestedSharedServicesInternetGateway
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-igw

  oSharedServicesNatGateway1:
    Description: The ID of the shared services first Natgateway
    Value: !Ref rNestedSharedServicesNatGateway1
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-ngw1

  oSharedServicesNatGateway2:
    Description: The ID of the shared services second Natgateway
    Value: !Ref rNestedSharedServices
    Export: 
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ngw2