AWSTemplateFormatVersion: 2010-09-09
Description: Creates an aws 3 tier arcitecture with nested stacks
Metadata: # This is putr in an s3 bucket
  AWS::CloudFormation::Interface:
    ParameterGroups: # This groups all the parameter acording to resources created
    - Label:
        default: "Account values"
      Parameters: 
        - pAwsAccount
        - pAwsAccountLC
        - pBucketName
        - pAppName
    - Label: 
        default: "Network configurations" 
      Parameters:
        - pVPCCidr
        - pPrivateSubnet1CIDR
        - pPrivateSubnet2CIDR
        - pPublicSubnet1CIDR
        - pPublicSubnet2CIDR
        - pAvailabilityZones
        - pSharedServicesAccount
        - pSharedServicesVPCCidr
        - pSharedServicesPrivateSubnet1CIDR
        - pSharedServicesPrivateSubnet2CIDR
        - pSharedServicesPublicSubnet1CIDR
        - pSharedServicesPublicSubnet2CIDR
        - pSharedServicesAvailabilityZones
    - Label:
        default: "Transit Gateway configurations" 
      Parameters: 
        - pAmazonAsn
        - pAutoAcceptAttachment
        - pRouteTablePropagation
        - pRouteTableAssociation
        - pDNSSupport
        - pVPNSupport
        - pSharedServicesPrivateSubnet1Id
        - pSharedServicesPrivateSubnet2Id
        - pSharedServicesVPCId
        - pApp1PrivateSubnet1Id
        - pApp1PrivateSubnet2Id
        - pApp1VPCId
        - pTransitGatewayCIDR
        - pApp1NatGateway1Id
        - pApp1NatGateway2Id
        - pSSNatGateway1Id
        - pSSNatGateway2Id
        - pSharedServicesInternetGateway
        - pSharedServicesPublicSubnet1Id
        - pSharedServicesPublicSubnet2Id

    ParameterLabels: # The default values will be presented on the console 
      pAwsAccount: 
        default: The account name in upper case. 
      pAwsAccountLC: 
        default: The account name in lower case 
      pBucketName: 
        default: The name of the bucket storing all the children stacks 
      pAppName: 
        default: The appplication being created 
  ###########################App vpc parameter labels############################################
      pVPCCidr: 
        default: The vpc cidr range 
      pPrivateSubnet1CIDR: 
        default: The first private subnet cidr range.
      pPrivateSubnet2CIDR: 
        default: The second private subnet cidr range 
      pPublicSubnet1CIDR: 
        default: The first public subnet cidr range
      pPublicSubnet2CIDR: 
        default: The second public subnet cidr range 
      pAvailabilityZones: 
        default: The availability zones on which the resource will be created 
  ###########################App shared services parameter labels#################################
      pSharedServicesAccount: 
        default: The vpc name for shared services 
      pSharedServicesVPCCidr: 
        default: The vpc cidr range for shared services vpc
      pSharedServicesPrivateSubnet1CIDR: 
        default: The first private subnet cidr range for shared services
      pSharedServicesPrivateSubnet2CIDR: 
        default: The second private subnet cidr range for shared services 
      pSharedServicesPublicSubnet1CIDR: 
        default: The first public subnet cidr range for shared services
      pSharedServicesPublicSubnet2CIDR: 
        default: The second public subnet cidr range for shared services
      pSharedServicesAvailabilityZones: 
        default: The availability zones on which the resource will be created for shared services
      pVpcid: 
        default: The vpc id on which the resources will be created 
#############################Transit gateway parameter labels######################################
      pAmazonAsn: 
        default: The Amazon side Autonomous System Number (ASN)
      pAutoAcceptAttachment: 
        default: Do you want to auto accept the tgw attachments?
      pRouteTablePropagation: 
        default: Do you want to automatically propagate the routes to the default route table?
      pRouteTableAssociation: 
        default: Do you want to automatically associate the routes to the default route table?
      pDNSSupport: 
        default:  Do you want to enable DNS suuport?
      pVPNSupport: 
        default: Do you want to enable VPN suuport? 
      pSharedServicesPrivateSubnet1Id: 
        default: The Id of the first shared services private subnet
      pSharedServicesPrivateSubnet2Id: 
        default: The Id of the second shared services private subnet
      pSharedServicesVPCId: 
        default: The Id of the shared services VPC
      pApp1PrivateSubnet1Id: 
        default: The Id of the first App1 private subnet 
      pApp1PrivateSubnet2Id: 
        default: The Id of the second App1 private subnet 
      pApp1VPCId: 
        default: The Id of the App1 VPC
      pTransitGatewayCIDR:
        default: The CIDR range for the transit gateway. Most likely /16 
      pApp1NatGateway1Id:
        default: The Id of the first Nat gateway
      pApp1NatGateway2Id:
        default: The Id of the second Nat gateway
      pSSNatGateway1Id: 
        default: The Id of the first shared services Nat gateway
      pSSNatGateway2Id: 
        default: The Id of the second shared services Nat gateway
      pSharedServicesInternetGateway: 
        default: The Internet gateway id for the shared services vpc
      pSharedServicesPublicSubnet1Id: 
        default: The Id of the first shared services public subnet
      pSharedServicesPublicSubnet2Id: 
        default: The Id of the second shared services public subnet
Parameters: 
####################### General parameter for all stacks #######################
  pAwsAccount:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccount
  
  pAwsAccountLC:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccountLC

  pBucketName:
    Type: String
    Default: prod-nested-stack-us-east-1
  
  pAppName:
    Type: String
    Default: InnovaSoft
########################## VPC parameters ######################################
  pVPCCidr:
    Type: String
    Default: 10.1.1.0/24
  
  pPrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
    Default: 10.1.1.0/27
  
  pPrivateSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
    Default: 10.1.1.32/27
  
  pPublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
    Default: 10.1.1.64/27
  
  pPublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
    Default: 10.1.1.96/27
  
  pAvailabilityZones:
    Type: CommaDelimitedList
    Default: us-east-1a, us-east-1b

########################## Shared services VPC parameters ######################################
  pSharedServicesAccount:
    Type: String
    Default: /standard/SharedServicesVpc
  
  pSharedServicesVPCCidr:
    Type: String
    Default: 10.1.2.0/24
  
  pSharedServicesPrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
    Default: 10.1.2.0/27
  
  pSharedServicesPrivateSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
    Default: 10.1.2.32/27
  
  pSharedServicesPublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
    Default: 10.1.2.64/27
  
  pSharedServicesPublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
    Default: 10.1.2.96/27
  
  pSharedServicesAvailabilityZones:
    Type: CommaDelimitedList
    Default: us-east-1a, us-east-1b
  # Security Group parameters
  pVpcid:
    Type: String 
  
  ################################ Transit Gateway ###############################################
  pAmazonAsn:
    Type: String
    Default: 65000
    MinLength: 5
    MaxLength: 10
    ConstraintDescription: The range is 64512 to 65534 for 16-bit ASNs and 4200000000 to 4294967294 for 32-bit ASNs.
  
  pAutoAcceptAttachment:
    Type: String
    Default: "enable"
    AllowedValues:
      - "enable"
      - "disable"
  
  pRouteTablePropagation:
    Type: String
    Default: "enable"
    AllowedValues:
      - "enable"
      - "disable"
  
  pRouteTableAssociation: 
    Type: String
    Default: "enable"
    AllowedValues:
      - "enable"
      - "disable"

  pDNSSupport:
    Type: String
    Default: "enable"
    AllowedValues:
      - "enable"
      - "disable"
  
  pVPNSupport:
    Type: String
    Default: "enable"
    AllowedValues:
      - "enable"
      - "disable"
  
  pSharedServicesPrivateSubnet1Id:
    Type: String

  pSharedServicesPrivateSubnet2Id:
    Type: String

  pSharedServicesVPCId:
    Type: String

  pApp1PrivateSubnet1Id:
    Type: String

  pApp1PrivateSubnet2Id:
    Type: String

  pApp1VPCId:
    Type: String
      
  pTransitGatewayCIDR:
    Type: String 
    Default: 10.1.0.0/16
  
  pApp1NatGateway1Id:
    Type: String
  
  pApp1NatGateway2Id:
    Type: String 
  
  pSSNatGateway1Id:
    Type: String 

  pSSNatGateway2Id:
    Type: String 

Resources: 
  rVpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${pBucketName}.s3.amazonaws.com/vpc.yaml
      TimeoutInMinutes: 20
      Parameters:
        pVPCCidr: !Ref pVPCCidr 
        pPrivateSubnet1CIDR: !Ref pPrivateSubnet1CIDR 
        pPrivateSubnet2CIDR: !Ref pPrivateSubnet2CIDR 
        pPublicSubnet1CIDR: !Ref pPublicSubnet1CIDR 
        pPublicSubnet2CIDR: !Ref pPublicSubnet2CIDR 
        pAppName: !Ref pAppName
        pAvailabilityZones:
          Fn::Join:
            - ','
            - !Ref pAvailabilityZones
  
  rSharedServicesVpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${pBucketName}.s3.amazonaws.com/sharedvpc.yaml
      TimeoutInMinutes: 20
      Parameters:
        pSharedServicesAccount: !Ref pSharedServicesAccount
        pSharedServicesVPCCidr: !Ref pSharedServicesVPCCidr 
        pSharedServicesPrivateSubnet1CIDR: !Ref pSharedServicesPrivateSubnet1CIDR 
        pSharedServicesPrivateSubnet2CIDR: !Ref pSharedServicesPrivateSubnet2CIDR 
        pSharedServicesPublicSubnet1CIDR: !Ref pSharedServicesPublicSubnet1CIDR 
        pSharedServicesPublicSubnet2CIDR: !Ref pSharedServicesPublicSubnet2CIDR 
        pSharedServicesAvailabilityZones:
          Fn::Join:
            - ','
            - !Ref pSharedServicesAvailabilityZones
        pAppName: !Ref pAppName

  rIAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${pBucketName}.s3.amazonaws.com/iam.yaml
      TimeoutInMinutes: 20
      Parameters: 
        pAppName: !Ref pAppName
  
  rTransitGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${pBucketName}.s3.amazonaws.com/TransitGateway.yaml
      TimeoutInMinutes: 20
      Parameters: 
        pAppName: !Ref pAppName
        pSharedServicesAccount: !Ref pSharedServicesAccount
        pAmazonAsn: !Ref pAmazonAsn
        pAutoAcceptAttachment: !Ref pAutoAcceptAttachment 
        pRouteTablePropagation: !Ref pRouteTablePropagation 
        pRouteTableAssociation: !Ref pRouteTableAssociation 
        pDNSSupport: !Ref pDNSSupport 
        pVPNSupport: !Ref pVPNSupport 
        pTransitGatewayCIDR: !Ref pTransitGatewayCIDR
        pSharedServicesPrivateSubnet1Id: 
          Fn::GetAtt: 
            - rSharedServicesVpcStack 
            - Outputs.oPrivateSubnet1
        pSharedServicesPrivateSubnet2Id: 
          Fn::GetAtt: 
            - rSharedServicesVpcStack 
            - Outputs.oPrivateSubnet2 
        pSharedServicesVPCId: 
          Fn::GetAtt: 
            - rSharedServicesVpcStack 
            - Outputs.oVPC 
        pApp1PrivateSubnet1Id: 
          Fn::GetAtt: 
            - rVpcStack 
            - Outputs.oPrivateSubnet1
        pApp1PrivateSubnet2Id: 
          Fn::GetAtt: 
            - rVpcStack
            - Outputs.oPrivateSubnet2
        pApp1VPCId: 
          Fn::GetAtt: 
            - rVpcStack
            - Outputs.oVPC
        pApp1NatGateway1Id:
          Fn::GetAtt: 
            - rVpcStack
            - Outputs.oNatGateway1
        pApp1NatGateway2Id:
          Fn::GetAtt: 
            - rVpcStack
            - Outputs.oNatGateway2
        pSSNatGateway1Id:
          Fn::GetAtt: 
            - rSharedServicesVpcStack
            - Outputs.oNatGateway1
        pSSNatGateway2Id:
          Fn::GetAtt: 
            - rSharedServicesVpcStack
            - Outputs.oNatGateway2
        pSharedServicesInternetGateway:
          Fn::GetAtt: 
            - rSharedServicesVpcStack
            - Outputs.oInternetGateway
        pSharedServicesPublicSubnet1Id:
          Fn::GetAtt: 
            - rSharedServicesVpcStack
            - Outputs.oPublicSubnet1
        pSharedServicesPublicSubnet2Id:
          Fn::GetAtt: 
            - rSharedServicesVpcStack
            - Outputs.oPublicSubnet2
        
    DependsOn: 
    - rSharedServicesVpcStack
    - rVpcStack

  
        
          


  
