AWSTemplateFormatVersion: 2010-09-09
Description: Creates the SSM document for directory services

Parameters: 
  pAwsAccount:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccount
  
  pAwsAccountLC:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccountLC
    
  pAppName:
    Description: The app cosuming these resources
    Type: String  

  pADName:
    Description: The directory DNS name
    Type: String

  pADAdminGroupName:
    Description: The name for the linux admin users
    Type: String
    
 
Resources: 
  rNestedLinuxSudoersFile:
    Type: AWS::SSM::Document
    Properties: 
      Name: !Sub ${ pAwsAccount }-${ pAppName }-SudoersFileDoc
      DocumentFormat: JSON
      DocumentType: Command
      Content: 
        schemaVersion: '2.2'
        description: "Document to add domain joined linux servers group to sudoers file"
        mainSteps:
          - action: "aws:runShellScript"
            name: "runBashScript"
            inputs:
              runCommand:
              - !Sub | 
                    #!/bin/bash                    
                    # Variables
                    AD_GROUP='${pADAdminGroupName}'
                    DOMAIN='${pADName}'
                    SUDOERS_FILE='/etc/sudoers'
                    AD_GROUP_ENTRY="%${DomainName}\\\\${AdGroup} ALL=(ALL) NOPASSWD: ALL"
                    # Check if the group exists in Active Directory
                    if id "${DomainName}\\\\${AdGroup}" &>/dev/null; then
                        echo "Group ${DomainName}\\\\${AdGroup} exists in Active Directory."
                        # Check if the group is already in the sudoers file
                        if grep -q "${DomainName}\\\\\\\\${AdGroup}" "$SUDOERS_FILE"; then
                            echo "Group ${DomainName}\\\\${AdGroup} is already in the sudoers file."
                        else
                            echo "Group ${DomainName}\\\\${AdGroup} is not in the sudoers file. Adding it..."
                            echo "$AD_GROUP_ENTRY" >> "$SUDOERS_FILE"
                            if [ $? -eq 0 ]; then
                                echo "Successfully added ${DomainName}\\\\${AdGroup} to the sudoers file with NOPASSWD."
                            else
                                echo "Failed to add ${DomainName}\\\\${AdGroup} to the sudoers file."
                            fi
                        fi
                    else
                        echo "Group ${DomainName}\\\\${AdGroup} does not exist in Active Directory."
                    fi
Outputs:
  oNestedLinuxSudoersFile:
    Description: Document for Linux servers to be added to the sudoers file
    Value: !Ref rNestedLinuxSudoersFile
    Export: 
      Name: !Sub ${ pAwsAccount }-${ pAppName }-LinuxSudoersFileJoin






