AWSTemplateFormatVersion: 2010-09-09
Description: Creates a maintenance window for all servers

Parameters: 
  pAwsAccount:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccount
  
  pAwsAccountLC:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccountLC
    
  pAppName:
    Type: String
    Default: cognitech

  pWindowsPatchWindow:
    Description: The name of the window for windows patching 
    Type: String
    Default: WindowsPatch

  pLinuxPatchWindow:
    Description: The name of the window for linux patching 
    Type: String
    Default: LinuxPatch

  pMaintenanceWindowSchedule:
    Description: The schedule for when the maintenance window happens
    Type: String
    Default: cron(0 0 ? * SUN *)


Resources:
  rWindowsMaintennace:
    Type: AWS::SSM::MaintenanceWindow
    Properties:
      AllowUnassociatedTargets: false
      Cutoff: 1
      Description: Maintenance Window to patch all windows servers
      Duration: 5
      Name: !Sub ${ pAwsAccount }-${ pAppName }-${ pWindowsPatchWindow }
      Schedule: !Ref pMaintenanceWindowSchedule
      ScheduleTimezone: US/Eastern

  rLinuxMaintennace:
    Type: AWS::SSM::MaintenanceWindow
    Properties:
      AllowUnassociatedTargets: false
      Cutoff: 1
      Description: Maintenance Window to patch all linux servers
      Duration: 5
      Name: !Sub ${ pAwsAccount }-${ pAppName }-${ pLinuxPatchWindow }
      Schedule: !Ref pMaintenanceWindowSchedule
      ScheduleTimezone: US/Eastern
  
  rWindowsMaintenanceWindowTarget:
    Type: AWS::SSM::MaintenanceWindowTarget
    Properties:
      WindowId: !Ref rWindowsMaintennace
      ResourceType: INSTANCE
      Targets:
      - Key: tag:PatchGroup
        Values:
        - Windows-PatchGroup
      OwnerInformation: SSM windows weekly patches
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-${ pWindowsPatchWindow }
      Description: Windows servers to be patched during the maintenance window
    DependsOn: rWindowsMaintennace

  rLinuxMaintenanceWindowTarget:
    Type: AWS::SSM::MaintenanceWindowTarget
    Properties:
      WindowId: !Ref rLinuxMaintennace
      ResourceType: INSTANCE
      Targets:
      - Key: tag:PatchGroup
        Values:
        - Linux-PatchGroup
      OwnerInformation: SSM linux weekly patches
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-${ pLinuxPatchWindow }
      Description: Linux servers to be patched during the maintenance window
    DependsOn: rLinuxMaintennace
  
  rMaintenanceWindowPatchTaskforwindows:
    Type: AWS::SSM::MaintenanceWindowTask
    Properties:
      Description: Apply patches to windows and linux servers with patch group tags
      MaxConcurrency: 5
      MaxErrors: 1
      Priority: 0
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-${ pWindowsPatchWindow }-Task
      TaskType: RUN_COMMAND
      WindowId:
        Ref: rWindowsMaintennace
      TaskArn: AWS-RunPatchBaseline
      TaskInvocationParameters:
        MaintenanceWindowRunCommandParameters:
          Parameters:
            Operation:
            - Install
            RebootOption:
            - NoReboot
      Targets:
      - Key: WindowTargetIds
        Values:
        - Ref: rWindowsMaintenanceWindowTarget

  rMaintenanceWindowPatchTaskforlinux:
    Type: AWS::SSM::MaintenanceWindowTask
    Properties:
      Description: Apply patches to windows and linux servers with patch group tags
      MaxConcurrency: 5
      MaxErrors: 1
      Priority: 0
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-${ pLinuxPatchWindow }-Task
      TaskType: RUN_COMMAND
      WindowId:
        Ref: rLinuxMaintennace
      TaskArn: AWS-RunPatchBaseline
      TaskInvocationParameters:
        MaintenanceWindowRunCommandParameters:
          Parameters:
            Operation:
            - Install
            RebootOption:
            - NoReboot
      Targets:
      - Key: WindowTargetIds
        Values:
        - Ref: rLinuxMaintenanceWindowTarget




