apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 4
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: njibrigthain100/brigthain:familinkDB
        ports:
        - containerPort: 5432
