AWSTemplateFormatVersion: 2010-09-09
Description: This creates the IAM role to be used by the ec2 instance
Parameters: 
  pAwsAccount:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccount
  
  pAwsAccountLC:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccountLC

  pAppName:
    Description: The app cosuming these resources
    Type: String
    Default: cognitech

Resources: 
  rNestedInstanceRole:
    Type: AWS::IAM::Role
    Metadata:
      Comment: This is the role to be used by the instance during the buid
    Properties: 
      RoleName: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-role
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              Service:
                - !Sub ec2.${AWS::URLSuffix}
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
        - !Sub arn:${AWS::Partition}:iam::aws:policy/EC2InstanceProfileForImageBuilder
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonEC2FullAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonS3FullAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/SecretsManagerReadWrite
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSDirectoryServiceFullAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonSSMDirectoryServiceAccess
      Path: /

  rNestedIAMProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: /
      Roles: 
        - Ref: rNestedInstanceRole
Outputs:
  oNestedIAMRoleArn:
    Description: The arn of the IAM role 
    Value: !GetAtt rNestedInstanceRole.Arn
    Export: 
      Name: Nested-iam-Role-Arn
    
  oNestedIAMRoleName:
    Description: The name of the IAM role
    Value: !Ref rNestedInstanceRole
    Export: 
      Name: Nested-iam-Role-Name
  
  oNestedIAMInstanceProfileName:
    Description: The name of the instance profile 
    Value: !Ref rNestedIAMProfile
    Export: 
      Name: Nested-iam-Instance-profile-Name
  