AWSTemplateFormatVersion: 2010-09-09
Description: This creates the IAM role to be used by the ec2 instance

Parameters: 
  pAwsAccount:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccount
  
  pAwsAccountLC:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccountLC

  pBucketName:
    Description: The name in which the codes are stored
    Type: String
    Default: prod-nested-stack-us-east-1
Mappings: 

Conditions: 

Resources: 
  rEC2ImageBuilderInstanceRole:
  Type: AWS::IAM::Role
  Metadata:
    Comment: This is the role to be used by the instance during the buid
  Properties: 
    AssumeRolePolicyDocument: 
      Statement:
        - Action:
          - sts: AssumeRole
          Effect: Allow
          Principal: 
            service:
              - !Sub 'ec2.${AWS::URLSuffix}'
      Version: '2012-10-17'
    ManagedPolicyArns: 
      - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/EC2InstanceProfileForImageBuilder
    Path: /EC2ImageBuilder/

# https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-iam-instanceprofile.html
rEC2ImageBuilderInstanceProfile:
  Type: AWS::IAM::InstanceProfile
  Properties: 
    Path: /EC2ImageBuilder/
    Roles: 
      - Ref: rEC2ImageBuilderInstanceRole:

# https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html
rEC2ImageBuilderInstanceRoleLoggingPolicy:
  Type: AWS::IAM::Policy
  Metadata:
    Comment: This policy allows the instance to save log files to an s3 bucket
  Properties: 
    PolicyName: ImageBuilderLogBucketPolicy
    Roles: 
      - Ref: rEC2ImageBuilderInstanceRole:
    PolicyDocument:
      version: '2012-10-17'
      Statement:
        - Action:
          - s3:PutObject
          -
          Effect: Allow
          Resource: "*"

Outputs: