AWSTemplateFormatVersion: 2010-09-09
Description: Creates a transit gateway to allow for vpc peering between vpc 

Parameters: 
  pAwsAccount:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccount
  
  pAwsAccountLC:
    Description: The account in which the resources will be created
    Type: AWS::SSM::Parameter::Value<String>
    Default: /standard/AWSAccountLC
  
  pAmazonAsn:
    Description: The Amazon side Autonomous System Number (ASN)
    Type: String
    Default: 65000
    MinLength: 5
    MaxLength: 10
    ConstraintDescription: The range is 64512 to 65534 for 16-bit ASNs and 4200000000 to 4294967294 for 32-bit ASNs.
  
  pAutoAcceptAttachment:
    Description: Do you want to auto accept the tgw attachments?
    Type: String
    Default: "enable"
    AllowedValues:
      - "enable"
      - "disable"
  pRouteTablePropagation:
    Description: Do you want to automatically propagate the routes to the default route table? 
    Type: String
    Default: "enable"
    AllowedValues:
      - "enable"
      - "disable"
  
  pRouteTableAssociation:
    Description: Do you want to automatically associate the routes to the default route table? 
    Type: String
    Default: "enable"
    AllowedValues:
      - "enable"
      - "disable"

  pDNSSupport:
    Description: Do you want to enable DNS suuport? 
    Type: String
    Default: "enable"
    AllowedValues:
      - "enable"
      - "disable"
  
  pVPNSupport:
    Description: Do you want to enable VPN suuport? 
    Type: String
    Default: "enable"
    AllowedValues:
      - "enable"
      - "disable"
  
  pAppName:
    Type: String
    Default: cognitech

  pSharedServicesPrivateSubnet1Id:
    Description: The Id of the first shared services private subnet
    Type: String

  pSharedServicesPrivateSubnet2Id:
    Description: The Id of the second shared services private subnet
    Type: String

  pSharedServicesVPCId:
    Description: The Id of the shared services VPC
    Type: String

  pApp1PrivateSubnet1Id:
    Description: The Id of the first App1 private subnet
    Type: String

  pApp1PrivateSubnet2Id:
    Description: The Id of the second App1 private subnet
    Type: String

  pApp1VPCId:
    Description: The Id of the App1 VPC
    Type: String
  
  pTransitGatewayCIDR:
    Description: The CIDR range for the transit gateway. Mostlikely /16 
    Type: String
  
  pSharedServicesPrivateSubnet1RT:
    Description: The route table for shared services private subnet 1
    Type: String

  pSharedServicesPrivateSubnet2RT:
    Description: The route table for shared services private subnet 1
    Type: String

  pApp1PrivateSubnet1RT:
    Description: The route table for App1 vpc private subnet 1
    Type: String

  pApp1PrivateSubnet2RT:
    Description: The route table for App1 vpc private subnet 1
    Type: String



Resources:
############################Transit gateway######################################
  rNestedTransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties: 
      AmazonSideAsn: !Ref pAmazonAsn
      AutoAcceptSharedAttachments: !Ref pAutoAcceptAttachment
      DefaultRouteTableAssociation: !Ref pRouteTableAssociation
      DefaultRouteTablePropagation: !Ref pRouteTablePropagation
      Description: All vpc attachment transit gateway 
      DnsSupport: !Ref pDNSSupport
      Tags: 
        - Key: Name
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-tgw
      VpnEcmpSupport: !Ref pVPNSupport
 ######################Transit gateway attachments############################### 
  rSharedServicesVpcTransitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties: 
      SubnetIds: 
        - !Ref pSharedServicesPrivateSubnet1Id 
        - !Ref pSharedServicesPrivateSubnet2Id
      Tags: 
        - Key: Name
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-shared-Services-Attachment
      TransitGatewayId: !Ref rNestedTransitGateway
      VpcId: !Ref pSharedServicesVPCId
  
  rApp1VpcTransitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties: 
      SubnetIds: 
        - !Ref pApp1PrivateSubnet1Id
        - !Ref pApp1PrivateSubnet2Id
      Tags: 
        - Key: Name
          Value: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-App1-Attachment
      TransitGatewayId: !Ref rNestedTransitGateway
      VpcId: !Ref pApp1VPCId
  
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-route.html
  rSharedServicesPrivateSubnet1Route:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: !Ref pTransitGatewayCIDR
      RouteTableId: !Ref pSharedServicesPrivateSubnet2RT
      TransitGatewayId: !Ref rNestedTransitGateway

  rSharedServicesPrivateSubnet2Route:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: !Ref pTransitGatewayCIDR
      RouteTableId: !Ref pSharedServicesPrivateSubnet1RT
      TransitGatewayId: !Ref rNestedTransitGateway

  rApp1PrivateSubnet1Route:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: !Ref pTransitGatewayCIDR
      RouteTableId: !Ref pApp1PrivateSubnet1RT
      TransitGatewayId: !Ref rNestedTransitGateway

  rApp1PrivateSubnet2Route:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: !Ref pTransitGatewayCIDR
      RouteTableId: !Ref pApp1PrivateSubnet2RT
      TransitGatewayId: !Ref rNestedTransitGateway
  
  
Outputs:
  oTransitGatewayId:
    Description: The Nested stack transit gateway 
    Value: !Ref rNestedTransitGateway
    Export:
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-tgwId 
  
  oSharedServicestgwAttachment:
    Description: The shared services attachment to the transit gateway 
    Value: !Ref rSharedServicesVpcTransitGatewayAttachment
    Export:
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-ss-tgw-attachment 
  
  oApp1tgwAttachment:
    Description: The App1 attachment to the transit gateway 
    Value: !Ref rApp1VpcTransitGatewayAttachment
    Export:
      Name: !Sub ${ pAwsAccount }-${ AWS::Region}-${ pAppName }-app1-tgw-attachment 