apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "int-preproduction-use1-GitHub-Credentials"
        objectType: "secretsmanager"
        jmesPath:
        - path: Username
          objectAlias: GITHUB_USERNAME
        - path: Password
          objectAlias: GITHUB_PASSWORD
        - path: GitHubAccessToken
          objectAlias: GITHUB_ACCESS_TOKEN
      - objectName: "int-preproduction-use1-shared-user-credentials20251222192402582800000001"
        objectType: "secretsmanager"
        jmesPath:
        - path: access_key_id 
          objectAlias: ACCESS_KEY
        - path: secret_access_key
          objectAlias: SECRET_KEY
  secretObjects:
  # This creates k8s secrets after the first pod is created and the secrets are fetched
  - secretName: github-secrets
    type: Opaque
    data:
    - objectName: GITHUB_USERNAME # This is the objectAlias defined above
      key: GITHUB_USERNAME # This is the key in the Kubernetes secret
    - objectName: GITHUB_PASSWORD
      key: GITHUB_PASSWORD
    - objectName: GITHUB_ACCESS_TOKEN
      key: GITHUB_ACCESS_TOKEN
  - secretName: user-secrets
    type: Opaque
    data:
    - objectName: ACCESS_KEY
      key: ACCESS_KEY
    - objectName: SECRET_KEY
      key: SECRET_KEY
