apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "int-preproduction-use1-shared-eks-mysql-db/rds-credentials20260104192941118700000001"
        objectType: "secretsmanager"
        jmesPath:
        - path: username
          objectAlias: DB_USERNAME
        - path: password
          objectAlias: DB_PASSWORD
        - path: host
          objectAlias: DB_HOST
      - objectName: "int-preproduction-use1-ansible-authentication2025122219263128620000000a"
        objectType: "secretsmanager"
        jmesPath:
        - path: username
          objectAlias: ANSIBLE_USERNAME
        - path: password
          objectAlias: ANSIBLE_PASSWORD
  secretObjects:
  # This creates k8s secrets after the first pod is created and the secrets are fetched
  - secretName: rds-secrets
    type: Opaque
    data:
    - objectName: DB_USERNAME # This is the objectAlias defined above
      key: DB_USERNAME # This is the key in the Kubernetes secret
    - objectName: DB_PASSWORD
      key: DB_PASSWORD
    - objectName: DB_HOST
      key: DB_HOST
  - secretName: ansible-secrets
    type: Opaque
    data:
    - objectName: ANSIBLE_USERNAME
      key: ANSIBLE_USERNAME
    - objectName: ANSIBLE_PASSWORD
      key: ANSIBLE_PASSWORD
