apiVersion: v1
kind: Pod
metadata:
  name: secrets-sync
spec:
  serviceAccountName: secrets # This is important as it links the pod to the IAM role via IRSA
  volumes:
  - name: user-creds
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "secrets"
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.9
    resources:
      requests:
        memory: "16Mi"
        cpu: "10m"
      limits:
        memory: "32Mi"
        cpu: "50m"
    volumeMounts:
    - name: user-creds
      mountPath: "/mnt/secrets-store"
      readOnly: true
    ports:
    - containerPort: 80
