apiVersion: v1
kind: Pod
metadata:
  name: hway
  labels:
    app: hway
spec:
  containers:
  - name: hway
    image: njibrigthain100/brigthain:hwv1
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "1000m"
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: rds-secrets
          key: DB_USERNAME
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: rds-secrets
          key: DB_PASSWORD
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: rds-secrets
          key: DB_HOST
    - name: ANSIBLE_USERNAME
      valueFrom:
        secretKeyRef:
          name: ansible-secrets
          key: ANSIBLE_USERNAME
    - name: ANSIBLE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ansible-secrets
          key: ANSIBLE_PASSWORD
    - name: ANSIBLE_PORT
      valueFrom:
        configMapKeyRef:
          name: secrets-config
          key: ANSIBLE_PORT
    ports:
    - containerPort: 80
