# This pod demonstrates using Kubernetes secrets that are synced from AWS Secrets Manager
# The init container waits for the secrets-sync pod to create the github-secrets before starting
# This ensures the main container has access to the required secrets on startup
apiVersion: v1
kind: Pod
metadata:
  name: hway
  labels:
    app: hway
spec:
  initContainers:
  - name: wait-for-secrets
    image: busybox:1.36
    command:
    - sh
    - -c
    - |
      echo "Waiting for secrets to be created..."
      until wget --spider -q http://kubernetes.default.svc/api/v1/namespaces/default/secrets/github-secrets 2>/dev/null || [ -f /tmp/skip ]; do
        echo "Secret github-secrets not found yet, waiting..."
        sleep 5
      done
      echo "Secrets are ready!"
  containers:
  - name: hway
    image: njibrigthain100/brigthain:hwv1
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "1000m"
    env:
    - name: GITHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: github-secrets
          key: GITHUB_USERNAME
    - name: GITHUB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: github-secrets
          key: GITHUB_PASSWORD
    - name: GITHUB_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-secrets
          key: GITHUB_ACCESS_TOKEN
    - name: ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: user-secrets
          key: ACCESS_KEY
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: user-secrets
          key: SECRET_KEY
    - name: ANSIBLE_PORT
      valueFrom:
        configMapKeyRef:
          name: secrets-config
          key: ANSIBLE_PORT
    ports:
    - containerPort: 80
