# This pod demonstrates automatic secret rotation using CSI volume mounts
# Secrets are mounted as files and automatically updated when they change in AWS Secrets Manager
# The CSI driver polls for changes (default: every 2 minutes) and updates the mounted files
# Note: Your application must read secrets from files instead of environment variables for rotation to work
apiVersion: v1
kind: Pod
metadata:
  name: hway-with-rotation
  labels:
    app: hway
spec:
  serviceAccountName: secrets # Required for IRSA (IAM Roles for Service Accounts) to access AWS Secrets Manager
  volumes:
  - name: secrets-volume
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "secrets" # References the SecretProviderClass that defines which secrets to fetch
  containers:
  - name: hway
    image: njibrigthain100/brigthain:hwv1
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "1000m"
    volumeMounts:
    - name: secrets-volume
      mountPath: "/mnt/secrets"
      readOnly: true
    env:
    # ConfigMap value (not rotated, but can be updated via ConfigMap changes)
    - name: ANSIBLE_PORT
      valueFrom:
        configMapKeyRef:
          name: secrets-config
          key: ANSIBLE_PORT
    # Secret file paths for application to read:
    # - /mnt/secrets/GITHUB_USERNAME
    # - /mnt/secrets/GITHUB_PASSWORD
    # - /mnt/secrets/GITHUB_ACCESS_TOKEN
    # - /mnt/secrets/ACCESS_KEY
    # - /mnt/secrets/SECRET_KEY
    #
    # Example code to read secrets in your application:
    # Python: 
    #   with open('/mnt/secrets/GITHUB_USERNAME', 'r') as f:
    #       github_username = f.read().strip()
    #
    # Node.js:
    #   const fs = require('fs');
    #   const githubUsername = fs.readFileSync('/mnt/secrets/GITHUB_USERNAME', 'utf8').trim();
    #
    # Go:
    #   username, _ := os.ReadFile("/mnt/secrets/GITHUB_USERNAME")
    #   githubUsername := strings.TrimSpace(string(username))
    ports:
    - containerPort: 80
